#!/usr/bin/env python3
"""Repository artifact manifest: what this checkout contains, hashed.

The paper's numbers are reproducible only if the *inputs* are pinned as
carefully as the code.  This script computes a SHA-256 over every class of
artifact the results depend on and stores them in one file
(:data:`MANIFEST_PATH`), so that a release can prove the committed results were
produced by the committed code from the committed data:

==================  ======================================================
section             what it covers
==================  ======================================================
``code``            every tracked Python source file plus ``pyproject.toml``
``library``         ``flylab/pharm/library.yaml``, the typed compound library
``graphs``          the derived MaleCNS cuts in ``data/derived/``
``literature``      the sourced datasets in ``data/literature/``
``paper``           the committed artifacts in ``papers/``
``dependencies``    the resolved versions of the dependency closure
==================  ======================================================

``verify_manifest`` returns a structured diff, and ``flylab manifest --check``
exits non-zero when a *fatal* section differs.  ``dependencies`` is deliberately
not fatal: a manifest is checked on machines other than the one that wrote it,
and a different patch release of numpy is a fact to report, not a reason to
fail a release.  Everything else is fatal, because a changed graph, library,
literature dataset or paper artifact means the committed results no longer
follow from the committed inputs.

``requirements-lock.txt`` (written by ``--lock``) records the versions the
committed results were produced with.  It is **not** a full environment
specification: it has no hashes, no platform pins and no transitive guarantee
beyond what was installed here.  Use it to reproduce the numbers, not to
certify a supply chain.

    python scripts/manifest.py --write        # (re)write artifact-manifest.json
    python scripts/manifest.py --check        # verify, exit 1 on mismatch
    python scripts/manifest.py --lock         # write requirements-lock.txt
    flylab manifest --check                   # the same thing through the CLI
"""

from __future__ import annotations

import argparse
import fnmatch
import hashlib
import json
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Mapping, Sequence

__all__ = [
    "MANIFEST_VERSION",
    "MANIFEST_PATH",
    "LOCKFILE_PATH",
    "SECTIONS",
    "FATAL_SECTIONS",
    "repo_root",
    "build_manifest",
    "write_manifest",
    "verify_manifest",
    "dependency_closure",
    "write_lockfile",
    "main",
]

MANIFEST_VERSION = "1.0"
MANIFEST_PATH = "artifact-manifest.json"
LOCKFILE_PATH = "requirements-lock.txt"

#: section -> the glob patterns (relative to the repository root) it covers
SECTIONS: dict[str, dict[str, Any]] = {
    "code": {
        "patterns": ("flylab/**/*.py", "scripts/*.py", "pyproject.toml"),
        "description": "tracked Python sources and the build metadata",
    },
    "library": {
        "patterns": ("flylab/pharm/library.yaml",),
        "description": "the typed compound library (schema v3)",
    },
    "graphs": {
        "patterns": ("data/derived/*.json",),
        "description": "the derived MaleCNS cuts; CI products, never hand-edited",
    },
    "literature": {
        "patterns": ("data/literature/*.yaml",),
        "description": "the sourced literature datasets",
    },
    "paper": {
        "patterns": (
            "papers/results.json",
            "papers/*.md",
            "papers/figures/*",
            "papers/tables/*",
        ),
        "description": "the committed paper artifacts regenerated by scripts/reproduce_paper.py",
    },
}

#: a mismatch in these sections fails a release
FATAL_SECTIONS: tuple[str, ...] = ("code", "library", "graphs", "literature", "paper")

#: never hashed, whatever a pattern says
EXCLUDE = ("**/__pycache__/**", "**/*.pyc", "**/.ipynb_checkpoints/**", "**/*.feather")


# --------------------------------------------------------------------------
# paths and hashing
# --------------------------------------------------------------------------
def repo_root(start: Path | None = None) -> Path:
    """The repository root: the nearest ancestor holding ``pyproject.toml``."""
    here = (start or Path(__file__)).resolve()
    for candidate in [here, *here.parents]:
        if (candidate / "pyproject.toml").exists():
            return candidate
    return Path.cwd()


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _excluded(rel: str) -> bool:
    return any(fnmatch.fnmatch(rel, pattern) for pattern in EXCLUDE)


def _tracked_files(root: Path) -> set[str] | None:
    """Paths git accounts for, or ``None`` outside a checkout.

    ``--cached --others --exclude-standard`` is the working tree as git sees
    it: everything committed plus everything new that is not ignored.  That is
    the right set for a manifest -- a build artifact or a ``*.feather`` cannot
    drift into the code hash, while a module added in this branch is covered
    before it is committed.  A file that was deleted but not committed drops
    out, because the glob pass below only keeps paths that exist on disk.
    """
    try:
        out = subprocess.run(
            ["git", "ls-files", "-z", "--cached", "--others", "--exclude-standard"],
            cwd=root,
            capture_output=True,
            check=True,
            timeout=30,
        )
    except Exception:
        return None
    return {name for name in out.stdout.decode("utf-8", "replace").split("\0") if name}


def _match(root: Path, patterns: Sequence[str], tracked: set[str] | None) -> list[str]:
    found: set[str] = set()
    for pattern in patterns:
        if tracked is not None:
            for rel in tracked:
                if fnmatch.fnmatch(rel, pattern) or (
                    "**/" in pattern and fnmatch.fnmatch(rel, pattern.replace("**/", ""))
                ):
                    found.add(rel)
        for path in sorted(root.glob(pattern)):
            if path.is_file():
                rel = path.relative_to(root).as_posix()
                if tracked is None or rel in tracked:
                    found.add(rel)
    return sorted(rel for rel in found if not _excluded(rel) and (root / rel).is_file())


def _section(root: Path, name: str, tracked: set[str] | None) -> dict[str, Any]:
    meta = SECTIONS[name]
    files = _match(root, meta["patterns"], tracked)
    entries = {rel: _sha256_file(root / rel) for rel in files}
    digest = _sha256_text("\n".join(f"{rel}\t{sha}" for rel, sha in sorted(entries.items())))
    return {
        "kind": "files",
        "description": meta["description"],
        "patterns": list(meta["patterns"]),
        "sha256": digest,
        "n_entries": len(entries),
        "entries": entries,
        "fatal": name in FATAL_SECTIONS,
    }


# --------------------------------------------------------------------------
# dependency closure
# --------------------------------------------------------------------------
_NAME_RE = re.compile(r"^\s*([A-Za-z0-9][A-Za-z0-9._-]*)")


def _requirement_name(text: str) -> str | None:
    match = _NAME_RE.match(str(text))
    return match.group(1).lower().replace("_", "-") if match else None


def _declared_dependencies(root: Path) -> list[str]:
    """Names from ``[project] dependencies`` and every optional-dependency group."""
    try:
        import tomllib
    except Exception:  # pragma: no cover - Python < 3.11
        return []
    try:
        data = tomllib.loads((root / "pyproject.toml").read_text())
    except Exception:  # pragma: no cover
        return []
    project = data.get("project") or {}
    names: list[str] = []
    for item in project.get("dependencies") or []:
        name = _requirement_name(item)
        if name:
            names.append(name)
    for group in (project.get("optional-dependencies") or {}).values():
        for item in group or []:
            name = _requirement_name(item)
            if name:
                names.append(name)
    return sorted(dict.fromkeys(names))


def dependency_closure(root: Path | None = None) -> dict[str, Any]:
    """The project's declared dependencies plus everything they pull in.

    Returns ``{"roots": [...], "packages": {name: version}, "missing": [...]}``.
    Requirements guarded by an ``extra ==`` marker are skipped: they belong to a
    dependency's own optional features, which this project never asks for.
    """
    from importlib import metadata

    base = root or repo_root()
    roots = _declared_dependencies(base)
    seen: set[str] = set()
    queue = list(roots)
    packages: dict[str, str] = {}
    missing: list[str] = []
    while queue:
        name = queue.pop(0)
        if name in seen:
            continue
        seen.add(name)
        try:
            dist = metadata.distribution(name)
        except Exception:
            missing.append(name)
            continue
        packages[dist.metadata["Name"] or name] = dist.version
        for requirement in dist.requires or []:
            if "extra ==" in requirement:
                continue
            child = _requirement_name(requirement)
            if child and child not in seen:
                queue.append(child)
    return {
        "roots": roots,
        "packages": dict(sorted(packages.items(), key=lambda kv: kv[0].lower())),
        "missing": sorted(missing),
    }


def _dependency_section(root: Path) -> dict[str, Any]:
    closure = dependency_closure(root)
    entries = dict(closure["packages"])
    digest = _sha256_text("\n".join(f"{k}=={v}" for k, v in sorted(entries.items())))
    return {
        "kind": "packages",
        "description": "resolved versions of the project's dependency closure",
        "patterns": [],
        "sha256": digest,
        "n_entries": len(entries),
        "entries": entries,
        "roots": closure["roots"],
        "missing": closure["missing"],
        "python": sys.version.split()[0],
        "fatal": False,
        "note": (
            "Informational: a manifest is verified on machines other than the one that "
            "wrote it, so a version difference is reported and never fails a check."
        ),
    }


LOCK_HEADER = """\
# FlyLab dependency lock -- the versions the committed results were produced with.
#
# Generated by `python scripts/manifest.py --lock` (equivalently `flylab manifest
# --lock`) from pip's installed set, filtered to this project's actual dependency
# closure: the names in pyproject's [project] dependencies and optional-dependencies,
# plus everything those require transitively.
#
# WHAT THIS IS:  the exact versions behind papers/results.json and the committed
#                manifest, enough to reproduce those numbers.
# WHAT IT IS NOT: a full environment specification. There are no artifact hashes,
#                no platform or Python-version pins, no build dependencies and no
#                guarantee about packages outside the closure. Do not treat it as a
#                supply-chain attestation.
#
# python {python}
# generated {generated}
"""


def write_lockfile(root: Path | None = None, path: Path | None = None) -> dict[str, Any]:
    """Write ``requirements-lock.txt`` for the dependency closure."""
    base = root or repo_root()
    target = Path(path) if path else base / LOCKFILE_PATH
    closure = dependency_closure(base)
    lines = [
        LOCK_HEADER.format(
            python=sys.version.split()[0],
            generated=datetime.now(timezone.utc).isoformat(timespec="seconds"),
        )
    ]
    lines += [f"{name}=={version}" for name, version in closure["packages"].items()]
    if closure["missing"]:
        lines.append(
            "# declared but not installed here: " + ", ".join(closure["missing"])
        )
    target.write_text("\n".join(lines) + "\n")
    return {
        "path": str(target),
        "n_packages": len(closure["packages"]),
        "missing": closure["missing"],
    }


# --------------------------------------------------------------------------
# build / verify
# --------------------------------------------------------------------------
def _git_sha(root: Path) -> str | None:
    try:
        out = subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=root, capture_output=True, text=True, timeout=10, check=True
        )
        return out.stdout.strip() or None
    except Exception:
        return None


def _flylab_version() -> str | None:
    try:
        import flylab

        return getattr(flylab, "__version__", None)
    except Exception:  # pragma: no cover
        return None


def build_manifest(root: Path | None = None) -> dict[str, Any]:
    """Hash every artifact class in the repository and return the manifest."""
    base = root or repo_root()
    tracked = _tracked_files(base)
    sections = {name: _section(base, name, tracked) for name in SECTIONS}
    sections["dependencies"] = _dependency_section(base)
    overall = _sha256_text(
        "\n".join(f"{name}\t{sections[name]['sha256']}" for name in sorted(sections) if sections[name]["fatal"])
    )
    return {
        "flylab_manifest_version": MANIFEST_VERSION,
        "kind": "flylab-artifact-manifest",
        "generated_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "flylab_version": _flylab_version(),
        "git_sha": _git_sha(base),
        "git_tracked": tracked is not None,
        "sections": sections,
        "fatal_sections": list(FATAL_SECTIONS),
        "sha256": overall,
        "note": (
            "Hashes of the inputs the committed results depend on. Regenerate with "
            "`flylab manifest --write` whenever code or data changes, and before tagging "
            "a release: `flylab manifest --check` is what the release workflow gates on."
        ),
    }


def write_manifest(manifest: Mapping[str, Any], path: Path | None = None) -> Path:
    """Write a manifest as pretty, key-sorted JSON."""
    target = Path(path) if path else repo_root() / MANIFEST_PATH
    target.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    return target


def verify_manifest(path: str | Path | None = None, root: Path | None = None) -> dict[str, Any]:
    """Compare the repository against a committed manifest.

    Returns ``{"ok", "sections": {name: {"ok", "added", "removed", "changed",
    "summary", "fatal"}}, "notes"}``.  ``ok`` is false only when a *fatal*
    section differs; a dependency difference lands in ``notes``.
    """
    base = root or repo_root()
    target = Path(path) if path else base / MANIFEST_PATH
    if not Path(target).exists():
        raise FileNotFoundError(
            f"{target} does not exist. Create it with `flylab manifest --write`."
        )
    committed = json.loads(Path(target).read_text())
    current = build_manifest(base)

    version = str(committed.get("flylab_manifest_version") or "")
    notes: list[str] = []
    if version.split(".")[0] != MANIFEST_VERSION.split(".")[0]:
        notes.append(
            f"manifest format {version or 'unknown'} was written by another version of this "
            f"tool (this one writes {MANIFEST_VERSION}); the comparison may be partial"
        )

    sections: dict[str, Any] = {}
    ok = True
    names = sorted(set(committed.get("sections") or {}) | set(current["sections"]))
    for name in names:
        was = dict((committed.get("sections") or {}).get(name) or {})
        now = dict(current["sections"].get(name) or {})
        was_entries = dict(was.get("entries") or {})
        now_entries = dict(now.get("entries") or {})
        added = sorted(set(now_entries) - set(was_entries))
        removed = sorted(set(was_entries) - set(now_entries))
        changed = sorted(
            key for key in set(was_entries) & set(now_entries) if was_entries[key] != now_entries[key]
        )
        fatal = bool(now.get("fatal", was.get("fatal", name in FATAL_SECTIONS)))
        matches = not (added or removed or changed)
        detail = []
        if added:
            detail.append(f"{len(added)} added")
        if removed:
            detail.append(f"{len(removed)} removed")
        if changed:
            detail.append(f"{len(changed)} changed")
        sections[name] = {
            "ok": matches,
            "fatal": fatal,
            "n_entries": len(now_entries),
            "sha256_committed": was.get("sha256"),
            "sha256_current": now.get("sha256"),
            "added": added,
            "removed": removed,
            "changed": [
                {"path": key, "committed": was_entries[key], "current": now_entries[key]}
                for key in changed
            ],
            "summary": (
                f"{len(now_entries)} entries match"
                if matches
                else ", ".join(detail) + f" (of {len(now_entries)} entries)"
            ),
        }
        if not matches:
            if fatal:
                ok = False
            else:
                notes.append(
                    f"section {name!r} differs ({', '.join(detail)}) but is not fatal: "
                    + str(now.get("note") or "informational only")
                )
    return {
        "ok": ok,
        "manifest": str(target),
        "manifest_generated_utc": committed.get("generated_utc"),
        "manifest_git_sha": committed.get("git_sha"),
        "current_git_sha": current.get("git_sha"),
        "sha256_committed": committed.get("sha256"),
        "sha256_current": current.get("sha256"),
        "sections": sections,
        "notes": notes,
        "how_to_fix": (
            "If the difference is intended, regenerate with `flylab manifest --write` and "
            "commit the manifest with the change that caused it."
        ),
    }


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------
def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--write", action="store_true", help="write the manifest")
    parser.add_argument("--check", action="store_true", help="verify the manifest; exit 1 on mismatch")
    parser.add_argument("--lock", action="store_true", help="write requirements-lock.txt")
    parser.add_argument("--path", default=None, help=f"manifest path (default {MANIFEST_PATH})")
    parser.add_argument("--json", action="store_true", help="print JSON")
    args = parser.parse_args(list(argv) if argv is not None else None)

    base = repo_root()
    target = Path(args.path) if args.path else base / MANIFEST_PATH

    if args.lock:
        written = write_lockfile(base)
        print(f"lock -> {written['path']}  ({written['n_packages']} packages)")

    if args.write:
        manifest = build_manifest(base)
        write_manifest(manifest, target)
        if args.json:
            print(json.dumps(manifest, indent=2, sort_keys=True))
        else:
            print(f"manifest -> {target}")
            for name, section in sorted(manifest["sections"].items()):
                print(f"  {name:13} {section['n_entries']:4d} entries  {section['sha256'][:12]}")

    if args.check or not (args.write or args.lock):
        try:
            diff = verify_manifest(target, base)
        except FileNotFoundError as exc:
            print(str(exc), file=sys.stderr)
            return 2
        if args.json:
            print(json.dumps(diff, indent=2, sort_keys=True))
        else:
            print(f"manifest check - {target}")
            for name, section in sorted(diff["sections"].items()):
                print(f"  {name:13} {'ok' if section['ok'] else 'MISMATCH':9} {section['summary']}")
                for entry in section["changed"][:10]:
                    print(f"      changed {entry['path']}")
                for entry in (section["added"] + section["removed"])[:10]:
                    print(f"      added/removed {entry}")
            for note in diff["notes"]:
                print(f"  note: {note}")
            if not diff["ok"]:
                print(f"  {diff['how_to_fix']}", file=sys.stderr)
        return 0 if diff["ok"] else 1
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
